// Mock data for dashboard UI until database is implemented

// ─── Item Types ────────────────────────────────────────

export const itemTypes = [
  { id: "type-snippet", name: "Snippet", icon: "Code", color: "#3b82f6", isSystem: true },
  { id: "type-prompt", name: "Prompt", icon: "Sparkles", color: "#8b5cf6", isSystem: true },
  { id: "type-command", name: "Command", icon: "Terminal", color: "#f97316", isSystem: true },
  { id: "type-note", name: "Note", icon: "StickyNote", color: "#fde047", isSystem: true },
  { id: "type-link", name: "Link", icon: "Link", color: "#10b981", isSystem: true },
  { id: "type-file", name: "File", icon: "File", color: "#6b7280", isSystem: true },
  { id: "type-image", name: "Image", icon: "Image", color: "#ec4899", isSystem: true },
] as const;

// ─── Current User ──────────────────────────────────────

export const currentUser = {
  id: "user-1",
  name: "John Doe",
  email: "john@devstash.io",
  image: null,
  isPro: false,
};

// ─── Collections ───────────────────────────────────────

export const collections = [
  {
    id: "col-1",
    name: "React Patterns",
    description: "Common React patterns and hooks",
    isFavorite: true,
    itemCount: 12,
    userId: "user-1",
    createdAt: "2026-01-10T00:00:00Z",
    updatedAt: "2026-04-01T00:00:00Z",
  },
  {
    id: "col-2",
    name: "Python Snippets",
    description: "Useful Python code snippets",
    isFavorite: false,
    itemCount: 8,
    userId: "user-1",
    createdAt: "2026-01-15T00:00:00Z",
    updatedAt: "2026-03-28T00:00:00Z",
  },
  {
    id: "col-3",
    name: "Context Files",
    description: "AI context files for projects",
    isFavorite: true,
    itemCount: 5,
    userId: "user-1",
    createdAt: "2026-02-01T00:00:00Z",
    updatedAt: "2026-04-02T00:00:00Z",
  },
  {
    id: "col-4",
    name: "Interview Prep",
    description: "Technical interview preparation",
    isFavorite: false,
    itemCount: 24,
    userId: "user-1",
    createdAt: "2026-01-20T00:00:00Z",
    updatedAt: "2026-03-30T00:00:00Z",
  },
  {
    id: "col-5",
    name: "Git Commands",
    description: "Frequently used git commands",
    isFavorite: true,
    itemCount: 15,
    userId: "user-1",
    createdAt: "2026-02-05T00:00:00Z",
    updatedAt: "2026-04-03T00:00:00Z",
  },
  {
    id: "col-6",
    name: "AI Prompts",
    description: "Curated AI prompts for coding",
    isFavorite: false,
    itemCount: 18,
    userId: "user-1",
    createdAt: "2026-02-10T00:00:00Z",
    updatedAt: "2026-03-25T00:00:00Z",
  },
];

// ─── Items ─────────────────────────────────────────────

export const items = [
  {
    id: "item-1",
    title: "useAuth Hook",
    description: "Custom authentication hook for React applications",
    content: "export function useAuth() {\n  const [user, setUser] = useState(null);\n  // ...\n}",
    url: null,
    language: "typescript",
    isFavorite: true,
    isPinned: true,
    typeId: "type-snippet",
    userId: "user-1",
    tags: ["react", "auth", "hooks"],
    createdAt: "2026-01-16T00:00:00Z",
    updatedAt: "2026-01-16T00:00:00Z",
  },
  {
    id: "item-2",
    title: "API Error Handling Pattern",
    description: "Fetch wrapper with exponential backoff retry logic",
    content: "async function fetchWithRetry(url: string, retries = 3) {\n  // ...\n}",
    url: null,
    language: "typescript",
    isFavorite: false,
    isPinned: true,
    typeId: "type-snippet",
    userId: "user-1",
    tags: ["api", "error-handling", "fetch"],
    createdAt: "2026-01-15T00:00:00Z",
    updatedAt: "2026-01-15T00:00:00Z",
  },
  {
    id: "item-3",
    title: "Git Rebase Workflow",
    description: "Step-by-step interactive rebase commands",
    content: "git fetch origin\ngit rebase -i origin/main",
    url: null,
    language: "bash",
    isFavorite: false,
    isPinned: false,
    typeId: "type-command",
    userId: "user-1",
    tags: ["git", "rebase"],
    createdAt: "2026-02-10T00:00:00Z",
    updatedAt: "2026-02-10T00:00:00Z",
  },
  {
    id: "item-4",
    title: "Code Review Prompt",
    description: "AI prompt for thorough code reviews",
    content: "Review this code for bugs, performance issues, and security vulnerabilities...",
    url: null,
    language: null,
    isFavorite: true,
    isPinned: false,
    typeId: "type-prompt",
    userId: "user-1",
    tags: ["ai", "code-review"],
    createdAt: "2026-02-20T00:00:00Z",
    updatedAt: "2026-02-20T00:00:00Z",
  },
  {
    id: "item-5",
    title: "Docker Compose Cheatsheet",
    description: "Common Docker Compose commands for development",
    content: "docker compose up -d\ndocker compose logs -f\ndocker compose down -v",
    url: null,
    language: "bash",
    isFavorite: false,
    isPinned: false,
    typeId: "type-command",
    userId: "user-1",
    tags: ["docker", "devops"],
    createdAt: "2026-03-01T00:00:00Z",
    updatedAt: "2026-03-01T00:00:00Z",
  },
  {
    id: "item-6",
    title: "React 19 Migration Notes",
    description: "Key changes and breaking updates in React 19",
    content: "# React 19 Migration\n\n- New `use` hook\n- Server Components by default\n- ...",
    url: null,
    language: null,
    isFavorite: false,
    isPinned: false,
    typeId: "type-note",
    userId: "user-1",
    tags: ["react", "migration"],
    createdAt: "2026-03-10T00:00:00Z",
    updatedAt: "2026-03-10T00:00:00Z",
  },
  {
    id: "item-7",
    title: "Tailwind CSS v4 Docs",
    description: "Official Tailwind CSS v4 documentation",
    content: null,
    url: "https://tailwindcss.com/docs",
    language: null,
    isFavorite: false,
    isPinned: false,
    typeId: "type-link",
    userId: "user-1",
    tags: ["tailwind", "css", "docs"],
    createdAt: "2026-03-15T00:00:00Z",
    updatedAt: "2026-03-15T00:00:00Z",
  },
  {
    id: "item-8",
    title: "Python List Comprehension",
    description: "Common list comprehension patterns",
    content: "squares = [x**2 for x in range(10)]\nfiltered = [x for x in items if x > 0]",
    url: null,
    language: "python",
    isFavorite: false,
    isPinned: false,
    typeId: "type-snippet",
    userId: "user-1",
    tags: ["python", "basics"],
    createdAt: "2026-03-20T00:00:00Z",
    updatedAt: "2026-03-20T00:00:00Z",
  },
];

// ─── Sidebar Counts ────────────────────────────────────

export const typeCounts = {
  Snippet: 24,
  Prompt: 18,
  Command: 15,
  Note: 12,
  File: 5,
  Image: 3,
  Link: 8,
};
